# Generated by Django 5.1.6 on 2025-10-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lightning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_outgoing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="memo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_hash",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="qr_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
