# Generated by Django 5.1.6 on 2025-10-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lightning",
            "0002_invoice_expires_at_invoice_is_outgoing_invoice_memo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="payment_request",
            field=models.TextField(),
        ),
    ]
