# Generated by Django 5.1.6 on 2025-10-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lightning", "0003_alter_invoice_payment_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="payment_hash",
            field=models.TextField(blank=True, null=True),
        ),
    ]
