"""
Django settings for wallet project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decimal import Decimal
from bitcoinlib import config
import bitcoinlib.db as m
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

APPEND_SLASH = False

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-eu61ealbj0*_hlv)t=0ura@=34bbfn!t6@eh)$4l45@&em2(k+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles", 
    "walletapp",
    'orders',
    'lightning',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'drf_spectacular',
    'django_otp',
    'django_otp.plugins.otp_email',
]# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # 'DEFAULT_RENDERER_CLASSES': [
    #     'rest_framework.renderers.JSONRenderer',
    # ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 20,
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'rest_framework.throttling.AnonRateThrottle',
    #     'rest_framework.throttling.UserRateThrottle'
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anon': '100/hour',
    #     'user': '1000/hour',
    #     'transaction': '10/minute',
    # },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'walletapp.utils.custom_exception_handler',
}

# API Documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'Bitcoin Mini Wallet API',
    'DESCRIPTION': 'Professional Bitcoin wallet management system with comprehensive API endpoints for wallet operations, transactions, and balance management.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/',
}



# Middleware
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    'django_otp.middleware.OTPMiddleware',
    'django.middleware.common.CommonMiddleware',
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "lightning.middlewares.BackgroundInvoiceMiddleware"
]
AUTHENTICATION_BACKENDS = [
    "walletapp.backends.EmailOrUsernameBackend",  # path to your backend
    "django.contrib.auth.backends.ModelBackend",  # keep the default
]
AUTH_USER_MODEL='walletapp.User'  # Custom user model

ROOT_URLCONF = "wallet.urls"
# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "https://6000-firebase-studio-1757614190106.cluster-cbeiita7rbe7iuwhvjs5zww2i4.cloudworkstations.dev",
    "https://umuhoratech-wallet.onrender.com",
    "http://localhost:3000",
    "https://wallet-btc-mini.vercel.app",
    "https://umuhora-wallet.vercel.app",
    'https://wallet-umuhora.vercel.app',
]

# Production-optimized Gmail settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 465  # Changed from 587
EMAIL_USE_SSL = True  # Changed from TLS
EMAIL_USE_TLS = False
EMAIL_HOST_USER = "testcomlab24@gmail.com"
EMAIL_HOST_PASSWORD = "nyhbfgzcvhsadrpp"
DEFAULT_FROM_EMAIL = f"Umuhora Wallet <{EMAIL_HOST_USER}>"
EMAIL_TIMEOUT = 30

# OTP settings
OTP_EMAIL_SENDER = DEFAULT_FROM_EMAIL
OTP_TOTP_ISSUER = "Umuhora Wallet"
OTP_EMAIL_SUBJECT = "Your Umuhora Wallet One-Time Code"
# Allow sending cookies/auth headers
CORS_ALLOW_CREDENTIALS = True

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wallet.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }
from decouple import config
DB_NAME = config("DB_NAME")
DB_NAME_BITCOIN = config("DB_NAME_BITCOIN")
DB_USER = config("DB_USER")
DB_PASSWORD = config("DB_PASSWORD")
DB_HOST = config("DB_HOST")
DB_PORT = config("DB_PORT", default=3306, cast=int)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT':DB_PORT,
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# ✅ Bitcoinlib Database URI
BITCOINLIB_DB = (
    f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME_BITCOIN}"
)


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Static files
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
# WhiteNoise static files storage for production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# settings.py

WALLET_SETTINGS = {
    'MIN_TRANSACTION_AMOUNT': Decimal('0.00001'),
}

FEE_ADDRESS = 'your_bitcoin_fee_address_here'  # Replace with actual Bitcoin address

