# Generated by Django 5.1.6 on 2025-07-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="bitcoin_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
