# Generated by Django 5.1.6 on 2025-07-30 10:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_wallet_bitcoin_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Bitcoin Transaction",
                "verbose_name_plural": "Bitcoin Transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="wallet",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Bitcoin Wallet",
                "verbose_name_plural": "Bitcoin Wallets",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Optional transaction comment"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="fee",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("0E-8"),
                help_text="Transaction fee in BTC",
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether the wallet is active"
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="last_sync",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time wallet was synced with Bitcoin network",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="wallet_name",
            field=models.CharField(
                blank=True,
                help_text="Bitcoin Core wallet name",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="address",
            field=models.CharField(
                help_text="Bitcoin address (sender or recipient)", max_length=62
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=8,
                help_text="Transaction amount in BTC (negative for outgoing)",
                max_digits=16,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="confirmations",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of network confirmations"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(
                help_text="Transaction timestamp from Bitcoin network"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="txid",
            field=models.CharField(
                help_text="Bitcoin transaction ID",
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid transaction ID format",
                        regex="^[a-fA-F0-9]{64}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("0E-8"),
                help_text="Current wallet balance in BTC",
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="bitcoin_address",
            field=models.CharField(
                blank=True,
                help_text="Primary Bitcoin address for receiving funds",
                max_length=62,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid Bitcoin address format",
                        regex="^[13][a-km-zA-HJ-NP-Z1-9]{25,34}$|^bc1[a-z0-9]{39,59}$|^tb1[a-z0-9]{39,59}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["wallet", "-timestamp"], name="wallet_tran_wallet__b97fb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["txid"], name="wallet_tran_txid_f51749_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type"], name="wallet_tran_transac_7debff_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="transaction",
            table="wallet_transaction",
        ),
        migrations.AlterModelTable(
            name="wallet",
            table="wallet_wallet",
        ),
    ]
