# Generated by Django 5.1.6 on 2025-10-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")],
                        default="buy",
                        max_length=10,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("on_chain", "On-Chain"), ("lightning", "Lightning")],
                        default="on_chain",
                        max_length=20,
                    ),
                ),
                ("amount_currency", models.CharField(default="USD", max_length=10)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(decimal_places=8, default=0, max_digits=18),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=8, default=0, max_digits=18),
                ),
                (
                    "payout_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Contains user account details to pay them during sell (e.g., mobile money, bank)",
                    ),
                ),
                ("payment_proof", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("awaiting_confirmation", "Awaiting Confirmation"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=200,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "btc_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "btc_amount",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                ("btc_txid", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ln_invoice",
                    models.TextField(
                        blank=True,
                        help_text="BOLT11 invoice for Lightning payments",
                        null=True,
                    ),
                ),
                ("ln_amount_sats", models.BigIntegerField(blank=True, null=True)),
                (
                    "ln_payment_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ln_paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "flow_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct API"),
                            ("redirect", "Redirect Page"),
                            ("otp", "OTP Verification"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="providers/default.png",
                        null=True,
                        upload_to="providers/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("internal", models.BooleanField(default=False)),
                ("api_url", models.URLField(blank=True, null=True)),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("api_secret", models.CharField(blank=True, max_length=255, null=True)),
                ("callback_url", models.URLField(blank=True, null=True)),
                ("contact_url", models.URLField(blank=True, null=True)),
                (
                    "payment_info",
                    models.JSONField(
                        blank=True, default=dict, help_text="Instructions for payment"
                    ),
                ),
                ("extra_config", models.JSONField(blank=True, default=dict)),
                (
                    "currencies",
                    models.JSONField(
                        default=list,
                        help_text="Supported currencies, e.g., ['BIF','USD']",
                    ),
                ),
                (
                    "exchange_rate_to_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=7500,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("percent", "Percentage")],
                        default="percent",
                        max_length=10,
                    ),
                ),
                (
                    "fee_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("can_buy", models.BooleanField(default=True)),
                ("can_sell", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
