# Generated by Django 5.1.6 on 2025-09-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="direction",
            field=models.CharField(
                choices=[("buy", "Buy"), ("sell", "Sell")], default="buy", max_length=10
            ),
        ),
    ]
