# Generated by Django 5.1.6 on 2025-09-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payout_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Contains user account details to pay them during sell (e.g., mobile money, bank)",
            ),
        ),
    ]
