# Generated by Django 5.1.6 on 2025-09-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_payout_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payout_data",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Contains user account details to pay them during sell (e.g., mobile money, bank)",
            ),
        ),
    ]
