# Generated by Django 5.1.6 on 2025-09-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_payout_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("awaiting_confirmation", "Awaiting Confirmation"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
    ]
