# Generated by Django 5.1.6 on 2025-10-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ln_amount_sats",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="ln_invoice",
            field=models.TextField(
                blank=True, help_text="BOLT11 invoice for Lightning payments", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="ln_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="ln_payment_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("on_chain", "On-Chain"), ("lightning", "Lightning")],
                default="on_chain",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("awaiting_confirmation", "Awaiting Confirmation"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
    ]
