# Generated by Django 5.1.6 on 2025-10-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_ln_amount_sats_order_ln_invoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=18, null=True
            ),
        ),
    ]
