# Generated by Django 5.1.6 on 2025-09-11 14:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_name", models.CharField(max_length=100, unique=True)),
                (
                    "bitcoin_address",
                    models.CharField(blank=True, max_length=62, null=True),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0.0"), max_digits=16
                    ),
                ),
                ("network", models.CharField(default="testnet", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txid", models.CharField(max_length=64, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("send", "Send"), ("receive", "Receive")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=8, max_digits=16)),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0.0"), max_digits=16
                    ),
                ),
                (
                    "service_fee",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0.0"), max_digits=16
                    ),
                ),
                (
                    "from_address",
                    models.CharField(blank=True, max_length=62, null=True),
                ),
                ("to_address", models.CharField(max_length=62)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confirmations", models.PositiveIntegerField(default=0)),
                ("raw_tx", models.TextField(blank=True, null=True)),
                ("tx_size_bytes", models.PositiveIntegerField(blank=True, null=True)),
                ("explorer_url", models.URLField(blank=True, null=True)),
                ("comment", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="walletapp.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
