# Generated by Django 5.1.6 on 2025-09-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walletapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
