# Generated by Django 5.1.6 on 2025-10-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walletapp", "0002_alter_transaction_to_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_otp_required",
            field=models.BooleanField(default=False),
        ),
    ]
