# Generated by Django 5.1.6 on 2025-10-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walletapp", "0002_alter_transaction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="is_service",
            field=models.BooleanField(default=False),
        ),
    ]
