# Generated by Django 5.1.6 on 2025-10-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walletapp", "0003_user_is_otp_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="network",
            field=models.CharField(default="bitcoin", max_length=20),
        ),
    ]
